ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from shoppingcart import urls as cart_urls
from forum import views
import forum

urlpatterns = [
    path('', cart_urls.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('accounts/', include('accounts.urls')),
    path('reset/', include('accounts.urls_reset')),
    path('shoppingcart/', include('shoppingcart.urls')),
    path('contact/', include('contact.urls')),
    path('', include('charts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

forum/urls.py
from django.urls import path, re_path, include
from . import views
from search import views as search_views
import forum

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('user/<str:username>/', views.UserPostListView.as_view(),
         name='user_posts'),
    re_path(r'^post/(?P<pk>\d+)/$', views.post_detail,
            name='post_detail'),
    path('posts/new/', views.CreatePostView.as_view(),
         name='post_new'),
    re_path(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(),
            name='post_edit'),
    re_path(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(),
            name='post_remove'),
    path('drafts/<str:username>/', views.DraftListView.as_view(),
         name='post_draft_list'),
    re_path(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post,
            name='add_comment_to_post'),
    re_path(r'^comment/(?P<pk>\d+)/edit/$', views.CommentUpdateView.as_view(),
            name='comment_edit'),
    re_path(r'^post/(?P<pk>\d+)/comment/(?P<id>\d+)/reply/$',
            views.add_reply_to_comment, name='add_reply_to_comment'),
    re_path(r'^post/(?P<pk>\d+)/comment/(?P<id>\d+)/reply/edit/$',
            views.edit_reply, name='edit_reply'),
    re_path(r'^reply/(?P<pk>\d+)/remove/$',
            views.reply_remove, name='reply_remove'),
    re_path(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve,
            name='comment_approve'),
    re_path(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove,
            name='comment_remove'),
    re_path(r'^post/(?P<pk>\d+)/publish/$', views.post_publish,
            name='post_publish'),
    path('search_posts/', search_views.search_posts,
         name='search_posts'),
    path('posts_results/<search_text>/', search_views.posts_results,
         name='posts_results'),
    path('search_drafts/', search_views.search_drafts,
         name='search_drafts'),
    path('drafts_results/<search_text>/', search_views.drafts_results,
         name='drafts_results'),
    re_path(r'^post/(?P<pk>\d+)/like/$', views.like_post,
            name='like_post'),
    re_path(r'^post/(?P<pk>\d+)/dislike/$', views.dislike_post,
            name='dislike_post'),
]

shoppingcart/urls.py
from django.urls import path, include
from .views import (
    CheckoutView,
    HomeView,
    PaymentView,
    OrderSummaryView,
    item_detail,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    delete_card,
    save_default_card,
    AddCouponView,
    RequestRefundView,
    UpdateCardView,
)
from search import urls as search_urls

urlpatterns = [
    path('product/<slug>/', item_detail , name='product'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order_summary/', OrderSummaryView.as_view(), name='order_summary'),
    path('home/', HomeView.as_view(), name='home'),
    path('add_to_cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add_coupon'),
    path('remove_from_cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart,
         name='remove_single_item_from_cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('payment/delete_card/<id>/', delete_card, name='delete_card'),
    path('payment/save_default_card/<id>/', save_default_card, name='save_default_card'),
    path('request_refund/', RequestRefundView.as_view(), name='request_refund'),
    path('update_card/<id>/', UpdateCardView.as_view(), name='update_card'),
    path('', include(search_urls))
]

shoppingcart/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
from PIL import Image

CATEGORY_CHOICES = (
    ('DRESSES', 'Dresses'),
    ('SHOES', 'Shoes'),
    ('SUITS', 'Suits'),
    ('VEILS', 'Veils'),
    ('RINGS', 'Rings'),
    ('FLOWERS', 'Flowers'),
    ('HAIR ACCESSORIES', 'Hair Accessories'),
    ('PURSES', 'Purses'),
    ('SHIRTS', 'Shirts'),
    ('BELTS', 'Belts'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Item(models.Model):
    """
    Item class that contains the details of an item. Has an add_to_cart
    and a remove_from_cart method for adding/removing products from
    the cart. The save method is overwritten so that the product image
    is resized.
    """
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=20)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("product", kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse("add_to_cart", kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse("remove_from_cart", kwargs={'slug': self.slug})

    def get_discount_price(self):
        if self.discount_price:
            total_price = self.price - self.discount_price
        return total_price

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.name)

    def get_choices(self):
        category_choices = []
        for category in CATEGORY_CHOICES:
            category_choices.append(category[1])
        return category_choices


class OrderItem(models.Model):
    """
    OrderItem class that makes the connection between
    order and item. Has a method that gets the total item
    price, a method that gets the total item discount price
    and another one that returns the amount of money saved.
    Also returns the final price depending if there is a
    discount on the item or not.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_item_discount_price(self):
        return self.get_total_item_price() - self.get_amount_saved()

    def get_amount_saved(self):
        return self.quantity * self.item.discount_price

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_item_discount_price()
        return self.get_total_item_price()


class Order(models.Model):
    """
    Order class that contains the details of an order.
    Has a method that gets the order summary total.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address',
        on_delete=models.SET_NULL, blank=True, null=True)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address',
        on_delete=models.SET_NULL, blank=True, null=True)
    use_default_shipping = models.BooleanField(default=False)
    use_default_billing = models.BooleanField(default=False)
    save_default_shipping = models.BooleanField(default=False)
    save_default_billing = models.BooleanField(default=False)
    same_billing_address = models.BooleanField(default=False)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    user_coupon = models.ForeignKey(
        'UserCoupon', on_delete=models.SET_NULL, blank=True, null=True)
    used_coupon = models.BooleanField(default=False)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    amount = models.IntegerField(blank=True, null=True)
    payment_option = models.CharField(max_length=10, default='payment')

    """
    Phases of an order:
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    """

    def __str__(self):
        return self.user.username

    """
    Get the total for all the items in the cart
    and only decrease the total if there is an user
    coupon that has not been used. The difference between
    the total of the items in the cart and the coupon amount
    should also be greater than 0.
    """

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
            self.amount = total
            self.save()
        if self.coupon and self.user_coupon and total - self.coupon.amount > 0:
            total -= self.coupon.amount
            self.amount = total
            self.save()
        return total

    """
    Get the total for all the items in the cart.
    If there is a coupon get the total
    regardless if the coupon was used or not
    or if the difference between the total of the items
    in the cart and the coupon amount is less than 0.
    This function is used for some checks in the
    'checkout.html' and 'order_summary.html' templates.
    """

    def get_total_with_coupon(self):
        total_with_coupon = 0
        for order_item in self.items.all():
            total_with_coupon += order_item.get_final_price()
        if self.coupon:
            total_with_coupon -= self.coupon.amount
        return total_with_coupon


class Address(models.Model):
    """Address details for a user"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    appartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip_code = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    """Payment details for an order done by a user"""
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL,
                             blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    """Coupon code for an order item"""
    code = models.CharField(max_length=15)
    amount = models.FloatField()
    valid_from = models.DateTimeField(blank=True, null=True)
    valid_to = models.DateTimeField(blank=True, null=True)
    active = models.BooleanField(default=True)
    number_of_usages_allowed = models.IntegerField(default=100)

    def __str__(self):
        return self.code


class UserCoupon(models.Model):
    """Coupon code for each user"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL,
                             blank=True, null=True)
    is_used = models.BooleanField(default=False)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)


class Refund(models.Model):
    """Refund details for an order"""
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.pk}"

shoppingcart/forms.py
from django import forms
from django_countries.fields import CountryField


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
)


class CheckoutForm(forms.Form):
    """
    Checkout form details, including a shipping address and
    a billing address. Has the options to use a default shipping
    address and to set the billing address the same as the
    shipping address.
    """
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_zip_code = forms.CharField(required=False)
    shipping_country = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_zip_code = forms.CharField(required=False)
    billing_country = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    """Coupon form that takes a code"""
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
    }))


class RefundForm(forms.Form):
    """
    Refund form with the reference code
    and a message
    """
    name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'name',
    }))
    email = forms.CharField(min_length=11, required=True,  widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'email',
        'type': 'email',
    }))
    ref_code = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'ref_code',
    }))
    message = forms.CharField(max_length=500, required=True, widget=forms.Textarea(attrs={
        'rows': 2,
        'class': 'form-control md-textarea',
        'id': 'message',
    }))


class PaymentForm(forms.Form):
    """
    Payment form with the stripe token and
    save and use_default fields for credit card
    """
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)
    delete_card = forms.CharField(required=False)
    
    
class UpdateCardForm(forms.Form):
    """
    Form for updating a credit/debit card
    """
    stripeToken = forms.CharField(required=False)

ecommerce/templates/shoppingcart/checkout.html
{% extends 'base.html' %} {% load crispy_forms_tags %} 
{% load countries %}
{% block custom_title %}
<title>Checkout</title>
{% endblock %} {% load static %} {% block content %}
<!-- Checkout form -->
<div class="container wow fadeIn">

  <!-- Heading -->
  <h2 class="my-5 h2 text-center">Checkout form</h2>

  <!--Grid row-->
  <div class="row">

    <!--Grid column-->
    <div class="col-md-8 mb-4">

      <!--Card-->
      <div class="card">

        <!--Card content-->
        <form method="POST" class="card-body">
          {% csrf_token %}

          <h3>Shipping address</h3>
          <div class="hideable_shipping_form">

            <!--address-->
            <div class="md-form mb-5">
              <input type="text" placeholder="1234 Main St" id="shipping_address" value="{{order.shipping_address.street_address}}" name="shipping_address" class="form-control" />
              <label for="shipping_address" class="">Address 1</label>
            </div>

            <!--address-2-->
            <div class="md-form mb-5">
              <input type="text" placeholder="Appartment or suite" id="shipping_address2" value="{{order.shipping_address.appartment_address}}" name="shipping_address2" class="form-control" />
              <label for="shipping_address2" class="">Address 2</label>
            </div>

            <!--Grid row-->
            <div class="row">
              <!--Grid column-->
              <div class="col-lg-4 col-md-12 mb-4">
                <label for="id_shipping_country">Country</label>{% get_countries as countries %}
                <select name="shipping_country" id="id_shipping_country" class="custom-select d-block w-100" >
                  {% if order.shipping_address.country %}
                    <option value="{{ order.shipping_address.country.code }}" selected>{{ order.shipping_address.country.name }}</option>
                    {% else %}
                    <option value="select-country" selected>(select country)</option>
                    {% endif %}
                  {% for country in countries %}
                    <option value="{{ country.code }}">{{ country.name }}</option>
                  {% endfor %}
                </select>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>

              <!--Grid column-->
              <div class="col-lg-4 col-md-6 mb-4">
                <label for="shipping_zip_code">Zip</label>
                <input type="text" placeholder="Zip code" id="shipping_zip_code" value="{{order.shipping_address.zip_code}}" name="shipping_zip_code" class="form-control" minlength='6' maxlength='12' />
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>

            <div class="custom-control custom-checkbox">
              {% if order.same_billing_address == True %}
              <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address" checked>
              {% else %}
              <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
              {% endif %}
              <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
            </div>
            <div class="custom-control custom-checkbox save-default-shipping">
              {% if order.save_default_shipping == True %}
              <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping" checked>
              {% else %}
               <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
               {% endif %}
              <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
            </div>
          </div>

          {% if default_shipping_address %}
          <div class="custom-control custom-checkbox use-default-shipping">
            {% if order.use_default_shipping == True %}
            <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping" checked> {% else %}
            <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping"> {% endif %}
            <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }} </label>
          </div>
          {% endif %}

          <hr>



          <h3>Billing address</h3>
          <div class="hideable_billing_form">

            <!--address-->
            <div class="md-form mb-5">
              <input type="text" placeholder="1234 Main St" id="billing_address" value="{{order.billing_address.street_address}}" name="billing_address" class="form-control" />
              <label for="billing_address" class="">Address 1</label>
            </div>

            <!--address-2-->
            <div class="md-form mb-5">
              <input type="text" placeholder="Appartment or suite" id="billing_address2" value="{{order.billing_address.appartment_address}}" name="billing_address2" class="form-control" />
              <label for="billing_address2" class="">Address 2</label>
            </div>

            <!--Grid row-->
            <div class="row">
              <!--Grid column-->
              <div class="col-lg-4 col-md-12 mb-4">
                <label for="id_billing_country">Country</label>
                {% get_countries as countries %}
                <select name="billing_country" id="id_billing_country" class="custom-select d-block w-100" >
                  {% if order.billing_address.country %}
                    <option value="{{ order.billing_address.country.code }}" selected>{{ order.billing_address.country.name }}</option>
                  {% else %}
                    <option value="select-country" selected>(select country)</option>
                  {% endif %}
                  {% for country in countries %}
                    <option value="{{ country.code }}">{{ country.name }}</option>
                  {% endfor %}
                </select>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>

              <!--Grid column-->
              <div class="col-lg-4 col-md-6 mb-4">
                <label for="billing_zip_code">Zip</label>
                <input type="text" placeholder="Zip code" id="billing_zip_code" value="{{order.billing_address.zip_code}}" name="billing_zip_code" class="form-control" minlength='6' maxlength='12' />
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>

            <div class="custom-control custom-checkbox save-default-billing">
              {% if order.save_default_billing == True %}
              <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing" checked>
              {% else %}
              <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
              {% endif %}
              <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
            </div>
          </div>

          {% if default_billing_address %}
          <div class="custom-control custom-checkbox use-default-billing">
            {% if order.use_default_billing == True %}
            <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing" checked> {% else %}
            <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing"> {% endif %}
            <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }} </label>
          </div>
          {% endif %}

          <hr>

          <h3>Payment option</h3>

          <div class="d-block my-3">
            {% for value, name in form.fields.payment_option.choices %}
            <div class="custom-control custom-radio">
              {% if order.payment_option == value %}
              <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" checked required>
              {% else %}
              <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" > {% endif %}
              <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
            </div>
            {% endfor %}
          </div>
          <hr class="mb-4">
          <a class="btn btn-primary" href="/shoppingcart/order_summary/">Back To Summary</a>
          <button class="btn btn-warning" type="submit">Continue to payment</button>
        </form>
      </div>
    </div>

    <!--Grid column-->
    <div class="col-md-4 mb-4">
      <!-- Order Snippet -->
      {% include 'includes/order_snippet.html' %}
    </div>
  </div>
</div>
{% endblock %} {% block custom_js %}
<script src="{% static 'js/custom/checkout.js' %}"></script>
{% endblock %}

ecommerce/templates/shoppingcart/product.html
{% extends 'base.html' %}
{% block custom_title %}
<title>{{ item.title }}</title>
{% endblock %}
{% block content %}


  <!--Product details-->
    <div class="container dark-grey-text mt-5">
      
      <!--Grid row-->
      <div class="row wow fadeIn">
        
        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <img src="{{ item.image.url }}" class="img-fluid product-image" alt="product-image">
        </div>

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="{% url 'filter_by_tags' category=item.category %}">
                <span class="badge badge-pill {{ item.get_label_display }}-color">{{ item.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if item.discount_price %}
                <span class="mr-1">
                  <del>£{{ item.price|floatformat }}</del>
                </span>
                <span>£{{ item.get_discount_price|floatformat }}</span>
              {% else %}
                <span>£{{ item.price|floatformat }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ item.description|linebreaks }}</p>

            <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ item.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">Remove from cart
            </a>
          </div>
        </div>
      </div>

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">
        <!--Grid column-->
        <div class="col-md-6 text-center">
          <h4 class="my-4 h4">Liked this? You'll also love these!</h4>
          <p> </p>
        </div>
      </div>


      <!--Grid row-->
      <div class="row wow fadeIn">
        {% for item in random_category_items %}
      <div class="col-lg-3 col-md-6 mb-4">

        <!--Card-->
        <div class="card">
        
            <!--Card image-->
            <div class="view overlay">
              <img src="{{ item.image.url }}" class="card-img-top" alt="product-image">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

          <!--Card content-->
          <div class="card-body text-center">
            <!--Category & Title-->
            <a href="{% url 'filter_by_tags' item.category %}" class="grey-text">
              <h5 class="badge badge-pill {{ item.get_label_display }}-color">{{ item.get_category_display }}</h5>
            </a>
            <h5>
              <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title|title }}
                    </a>
                  </strong>
            </h5>
            <h4 class="font-weight-bold blue-text">
              {% if item.discount_price %}
              <span class="mr-1">
                  <del>£{{ item.price|floatformat }}</del>
                </span>
              <span>£{{ item.get_discount_price|floatformat }}</span> {% else %}
              <span>£{{ item.price|floatformat }}</span> {% endif %}
          </div>
        </div>

      </div>
      {% endfor %}
      </div>
    </div>
{% endblock %}

ecommerce/templates/shoppingcart/update_card.html
{% extends 'base.html' %} {% load static %} {% block custom_css %}
<link rel="stylesheet" href="{% static 'css/custom/stripe.css' %}" type="text/css" /> {% endblock %} {% block custom_title %}
<title>Update Card Details</title>
{% endblock %} {% block content %}

<div class="container wow fadeIn">

    <!-- Update Card Heading -->
    <h2 class="my-5 h2 text-center">Update Card</h2>

    <!--Grid row-->
    <div class="row">

        <!--Grid column-->
        <div class="col-md-12 mb-4">

            <!--Card-->
            <div class="card">

                <!-- Form for updating card details by creating a new token -->
                <script src="https://js.stripe.com/v3/"></script>
                <form action="." method="POST" class="stripe-form" id="stripe-form">
                    {% csrf_token %}
                    <div class="stripe-form-row" id="creditCard">
                        <label for="private-stripe-element" id="stripeBtnLabel">Credit or debit card</label>
                        <div id="card-element" class="StripeElement StripeElement--empty">
                        </div>
                    </div>
                    <div class="stripe-form-row">
                        <button id="stripeBtn">Update Card Details</button>
                    </div>
                    <!-- Used to display form errors. -->
                    <div id="card-errors" role="alert"></div>
                </form>
            </div>
        </div>
        <div class="col-md-12">
            <a class="btn btn-primary no-margins-btn" href="/shoppingcart/payment/stripe/">Back To Payment</a>
        </div>
    </div>

</div>

</div>
{% endblock %} {% block custom_js %}
<script src="{% static 'js/library/stripe.js' %}"></script>
{% endblock %}